accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<str:username>/following-list/', views.following_list, name='following_list'),
    path('profile/<str:username>/followers-list/', views.followers_list, name='followers_list'),
    path('priority_list/<str:username>/', views.priority_list, name='priority_list'),
]

camping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from .views import main, get_weather


urlpatterns = [
    path('', views.main, name='main'),
    path('get-weather/', get_weather, name='get-weather'),
    path('sales/', views.sales, name='sales'),
    path('get_posts_by_sido/', views.get_posts_by_sido, name='get_posts_by_sido'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('reviews/', include('reviews.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
    path('schedules/', include('schedules.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:category>', views.category, name='category'),
    path('city/', views.city, name='city'),
    path('theme/', views.theme, name='theme'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/visits/', views.visits, name='visits'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
    path('update_priority_lists/', views.update_priority_lists, name='update_priority_lists'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('<int:post_pk>/create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    # path('<int:review_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),
    path('<int:review_pk>/likes/', views.review_likes, name='review_likes'),
    path('<int:review_pk>/dislikes/', views.review_dislikes, name='review_dislikes'),
]

reviews/models.py
from django.db import models
from posts.models import Post
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.utils import timezone
from datetime import timedelta,datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Review(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextUploadingField(blank=True,null=True)
    rating = models.IntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # emote_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='emote_reviews', through='Emote')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_reviews')

    def rate_to_star(self):
        return '★' * self.rating
    
    def rate_to_empty_star(self):
        return '☆' * (5 - self.rating)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return self.strftime('%Y-%m-%d')
    
    def save(self, *args, **kwargs):
        self.post.rating = (self.post.rating*self.post.reviews.count() + self.rating) / (self.post.reviews.count() + 1)
        self.post.save()
        super(Review, self).save(*args, **kwargs)


# class Emote(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     review = models.ForeignKey(Review, on_delete=models.CASCADE)
#     emotion = models.CharField(max_length=10)

reviews/forms.py
from django import forms
from .models import Review
from ckeditor.widgets import CKEditorWidget


class ReviewForm(forms.ModelForm):
    title = forms.CharField(
        label = False,
        widget = forms.TextInput(
            attrs = {
                'placeholder':'리뷰제목',
                'class': 'form-box',
            }
        )
    )

    # content = forms.CharField(
    #     label = '리뷰 내용',
    #     widget = CKEditorWidget())

    
    class Meta:
        model = Review
        fields = ('title', 'content', )

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm
from posts.models import Post
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.

@login_required
def create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    rating = request.POST.get('rating')
    if rating is None:
        rating = 5
    else:
        try:
            rating = int(rating)
        except ValueError:
            rating = 5
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.post = post
            review.rating = rating
            review.save()
            return redirect('posts:detail', post_pk)
    else:
        review_form = ReviewForm()
    context = {
        'review_form': review_form,
        'post': post,
    }
    return render(request, 'reviews/create.html', context)


@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    rating = request.POST.get('rating')
    if rating is None:
        rating = 5
    else:
        try:
            rating = int(rating)
        except ValueError:
            rating = 5
    if request.user == review.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review.rating = rating
                review_form.save()
                return redirect('reviews:detail', review.pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            'review_form': review_form,
            'review': review,
        }
        return render(request, 'reviews/update.html', context)
    else:
        return redirect('posts:detail', review.post.pk)


@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if review.user == request.user:
        review.delete()
    return redirect('posts:detail', review.post.pk)


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    context = {
        'review': review,
    }
    return render(request, 'reviews/detail.html', context)


# @login_required
# def emotes(request, review_pk, emotion):
#     review = Review.objects.get(pk=review_pk)
    
#     my_emote = Emote.objects.filter(review=review, user=request.user)
#     input_emote = Emote.objects.filter(review=review, user=request.user, emotion=emotion)

#     # 기존에 좋아요/싫어요 버튼을 누른 경우 지금 누른 버튼이라면 삭제, 다른 버튼이라면 동작하지 않도록!
#     alert = False
#     if my_emote.exists():
#         is_checked = False
#         if input_emote.exists():
#             input_emote.delete()
#         else:
#             alert = True
#     else:
#         Emote.objects.create(review=review, user=request.user, emotion=emotion)
#         is_checked = True
    
#     cnt = Emote.objects.filter(review=review, emotion=emotion).count()
#     context = {
#         'is_checked': is_checked,
#         'cnt': cnt,
#         'alert': alert,
#     }
#     return JsonResponse(context)


@login_required
def review_likes(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        r_is_liked = False
    else:
        review.like_users.add(request.user)
        r_is_liked = True
    context = {
        'r_is_liked': r_is_liked,
        'review_likes_count': review.like_users.count(),
        'r_is_disliked': request.user in review.dislike_users.all(),
        'review_dislikes_count': review.dislike_users.count(),
    }
    return JsonResponse(context)


@login_required
def review_dislikes(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user in review.dislike_users.all():
        review.dislike_users.remove(request.user)
        r_is_disliked = False
    else:
        review.dislike_users.add(request.user)
        r_is_disliked = True
    context = {
        'r_is_disliked': r_is_disliked,
        'review_dislikes_count': review.dislike_users.count(),
        'r_is_liked': request.user in review.like_users.all(),
        'review_likes_count': review.like_users.count(),
    }
    return JsonResponse(context)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 리뷰작성 {% endblock title %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reviews.css' %}"> 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock head %}
{% block content %}
<div class="review--write">
  <form action="{% url 'reviews:create' post.pk %}" method ="POST" id="review-form">
    {% csrf_token %}
    <div class='d-flex align-items-center gap-2'>
        <label for="rating">별점:</label>
        <div class="star-rating">
          <input id="star-1" name="rating" type="radio" value="1" />
          <label class="star-label rating--orange" for="star-1" title="1 star"></label>
          <input id="star-2" name="rating" type="radio" value="2" />
          <label class="star-label rating--orange" for="star-2" title="2 stars"></label>
          <input id="star-3" name="rating" type="radio" value="3" />
          <label class="star-label rating--orange" for="star-3" title="3 stars"></label>
          <input id="star-4" name="rating" type="radio" value="4" />
          <label class="star-label rating--orange" for="star-4" title="4 stars"></label>
          <input id="star-5" name="rating" type="radio" value="5" />
          <label class="star-label rating--orange" for="star-5" title="5 stars"></label>
        </div>
      </div>
      {{ review_form.as_p }}
      {{ review_form.media }}
        <input type="submit" value='리뷰작성' class="review--btn">
        <input type="submit" value="뒤로가기" onclick=window.history.back() class="review--btn">
  </form>
</div>
{% endblock content %}
{% block script %}
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/translations/ko.js"></script>
<script>
  ClassicEditor.create( document.querySelector( '#editor' ), {
    language: "ko"
  } );

  const stars = document.querySelectorAll('.star-rating label');
  const ratingInput = document.querySelector('input[name="rating"]');

  ratingInput.value = 5;
  stars.forEach(star => star.classList.add('rating--orange'));

  stars.forEach((star, index) => {
    star.addEventListener('click', () => {
      ratingInput.value = index + 1;
      for (let i = 0; i < stars.length; i++) {
        if (i <= index) {
          stars[i].classList.remove('rating--gray');
          stars[i].classList.add('rating--orange');
        } else {
          stars[i].classList.remove('rating--orange');
          stars[i].classList.add('rating--gray');
        }
      }
    });
  });
</script>
{% endblock script %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}
{% block title %} {{review.title}} {% endblock title %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reviews.css' %}"> 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock head %}
{% block content %}
<div class="review--container">

  <div class="review--header">
    <div class="d-flex gap-1">
    <i class="bi bi-bookmark-heart"></i>{{ review.post.title }} 이용 후기
      {% comment %} rating {% endcomment %}
      <div class="star-box">
        <span class="star-gray">
          <span class="star-orange" style="width:{{ review.rating|multiply_by_20 }}%;"></span>
        </span>
      </div>
    </div>
    <div>
      <a href="" onclick="copy_trackback(this.href); return false;" style="color:black;"><i class="bi bi-link-45deg"></i></a>
      <a href="" onclick="printThis(); return false;" style="color:black;"><i class="bi bi-printer"></i></a>
    </div>
  </div>

  <div class="review--title">
    {{ review.title }}

    <div class="review--info">
      <a class="review--user " href="{% url 'accounts:profile' review.user %}">
        {% if review.user.image %}
          <img src="{{ review.user.image.url }}" alt="{{ review.user}}">
        {% else %}
          <img src="{% static 'image/profile-none.png' %}" alt="profile-image-none">
        {% endif %}
        <span>{{ review.user}}</span>
      </a>
      <span>|</span>
      {{ review.created_string }}
      <span>|</span>

      <div class="d-flex align-items-center justify-content-center">
        {% comment %} 좋아요 {% endcomment %}
        {% if request.user.is_authenticated %}
        <form id="review-likes-form-{{ review.pk }}" data-review-id="{{ review.pk }}">
          {% csrf_token %}
          {% if request.user in review.like_users.all %}
          <button class="btn btn-link text-primary p-0" type="submit" {% if user in review.dislike_users.all %} disabled {% endif %}>
                <i class="bi bi-hand-thumbs-up-fill" id="review-up"></i>
              </button>
            {% else %}
              <button class="btn btn-link text-primary p-0" type="submit" {% if user in review.dislike_users.all %} disabled {% endif %}>
                <i class="bi bi-hand-thumbs-up" id="review-up"></i>
              </button>
            {% endif %}
          </form>
          {% else %}
          <button class="btn btn-link text-secondary p-0" disabled>
            <i class="bi bi-hand-thumbs-up" id="review-up"></i>
          </button>
          {% endif %}
          <span id="review-likes-count" class="count--like">{{ review.like_users.all|length }}</span>
        {% comment %} 싫어요 {% endcomment %}
        {% if request.user.is_authenticated %}
          <form id="review-dislikes-form-{{ review.pk }}" data-review-id="{{ review.pk }}">
            {% csrf_token %}
            {% if request.user in review.dislike_users.all %}
              <button class="btn btn-link text-primary p-0" type="submit" {% if user in review.like_users.all %} disabled {% endif %}>
                <i class="bi bi-hand-thumbs-down-fill" id="review-down"></i>
              </button>
            {% else %}
              <button class="btn btn-link text-primary p-0" type="submit" {% if user in review.like_users.all %} disabled {% endif %}>
                <i class="bi bi-hand-thumbs-down" id="review-down"></i>
              </button>
            {% endif %}
          </form>
        {% else %}
          <button class="btn btn-link text-secondary p-0" disabled>
            <i class="bi bi-hand-thumbs-down" id="review-down"></i>
          </button>
        {% endif %}
        <span id="review-dislikes-count" class="count--like">{{ review.dislike_users.all|length }}</span>
      </div>
    </div>
  </div>

    {% comment %} 리뷰 수정, 삭제 {% endcomment %}
    <div class="review--btn--box">
      {% if request.user == review.user %}
        <a href="{% url 'reviews:update' review.pk %}" class="reviews--btn">수정</a>
        <form action="{% url 'reviews:delete' review.pk %}" method="POST">
          {% csrf_token %}
          <input type="submit" value="삭제" class="reviews--btn" onclick="return confirm('삭제하시겠습니까?')">
        </form>
      {% endif %}
    </div>

    {% comment %} review {% endcomment %}
    <div class="review--body">
      {{ review.content|safe }}
    </div>
    <hr>

    <a href="{% url 'posts:detail' review.post.pk %}" class="list--view">게시글보기</a>

</div>
{% endblock content %}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static '/js/reviews_detail.js' %}" type="text/javascript"></script>
<script>
  function copy_trackback(url) {
    var tempInput = document.createElement('input');
    tempInput.value = url;
    document.body.appendChild(tempInput);
    tempInput.select();
    document.execCommand('copy');
    document.body.removeChild(tempInput);
    alert('URL이 복사되었습니다.');
  }
  
  function printThis() {
    window.print();
  }
  </script>
{% endblock script %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}리뷰수정{% endblock title %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reviews.css' %}"> 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock head %}
{% block content %}
<div class="review--write">
  <form action="{% url 'reviews:update' review.pk %}" method ="POST" id="review-form">
    {% csrf_token %}
    <div class='d-flex align-items-center gap-2'>
        <label for="rating">별점:</label>
        <div class="star-rating">
          <input id="star-1" name="rating" type="radio" value="1" />
          <label class="star-label rating--orange" for="star-1" title="1 star"></label>
          <input id="star-2" name="rating" type="radio" value="2" />
          <label class="star-label rating--orange" for="star-2" title="2 stars"></label>
          <input id="star-3" name="rating" type="radio" value="3" />
          <label class="star-label rating--orange" for="star-3" title="3 stars"></label>
          <input id="star-4" name="rating" type="radio" value="4" />
          <label class="star-label rating--orange" for="star-4" title="4 stars"></label>
          <input id="star-5" name="rating" type="radio" value="5" />
          <label class="star-label rating--orange" for="star-5" title="5 stars"></label>
        </div>
      </div>
      {{ review_form.as_p }}
      {{ review_form.media }}
        <input type="submit" value='리뷰수정' class="review--btn">
        <input type="submit" value="뒤로가기" onclick=window.history.back() class="review--btn">
  </form>
</div>
{% endblock content %}
{% block script %}
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/translations/ko.js"></script>
<script>
  ClassicEditor.create( document.querySelector( '#editor' ), {
    language: "ko"
  } );

  const stars = document.querySelectorAll('.star-rating label');
  const ratingInput = document.querySelector('input[name="rating"]');

  ratingInput.value = 5;
  stars.forEach(star => star.classList.add('rating--orange'));

  stars.forEach((star, index) => {
    star.addEventListener('click', () => {
      ratingInput.value = index + 1;
      for (let i = 0; i < stars.length; i++) {
        if (i <= index) {
          stars[i].classList.remove('rating--gray');
          stars[i].classList.add('rating--orange');
        } else {
          stars[i].classList.remove('rating--orange');
          stars[i].classList.add('rating--gray');
        }
      }
    });
  });
</script>
{% endblock script %}