accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<str:username>/following-list/', views.following_list, name='following_list'),
    path('profile/<str:username>/followers-list/', views.followers_list, name='followers_list'),
    path('priority_list/<str:username>/', views.priority_list, name='priority_list'),
]

camping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from .views import main, get_weather


urlpatterns = [
    path('', views.main, name='main'),
    path('get-weather/', get_weather, name='get-weather'),
    path('sales/', views.sales, name='sales'),
    path('get_posts_by_sido/', views.get_posts_by_sido, name='get_posts_by_sido'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('reviews/', include('reviews.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
    path('schedules/', include('schedules.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:category>', views.category, name='category'),
    path('city/', views.city, name='city'),
    path('theme/', views.theme, name='theme'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/visits/', views.visits, name='visits'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
    path('update_priority_lists/', views.update_priority_lists, name='update_priority_lists'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os
from django.conf import settings


class User(AbstractUser):
    SEOUL = '서울'
    INCHEON = '인천'
    BUSAN = '부산'
    ULSAN = '울산'
    DAEGU = '대구'
    GWANGJU = '광주'
    DAEJEON = '대전'
    SEJONG = '세종특별자치시'
    JEJU = '제주특별자치도' 
    GYEONGGI = '경기'
    GANGWON = '강원'
    CHUNGBUK = '충북'
    CHUNGNAM = '충남'
    JEONBUK = '전북'
    JEONNAM = '전남'
    GYEONGBUK = '경북'
    GYEONGNAM = '경남'
    REGION_CHOICES = [
        (SEOUL, '서울'), (INCHEON, '인천'), (BUSAN, '부산'), (ULSAN, '울산'), (DAEGU, '대구'), (GWANGJU, '광주'), (DAEJEON, '대전'), (SEJONG, '세종특별자치시'), (JEJU, '제주특별자치도'), (GYEONGGI, '경기'), (GANGWON, '강원'), (CHUNGBUK, '충북'), (CHUNGNAM, '충남'), (JEONBUK, '전북'), (JEONNAM, '전남'), (GYEONGBUK, '경북'),(GYEONGNAM, '경남'),
    ]
    OWNER = '사장님'
    CUSTOMER = '고객님'
    USER_TYPE_CHOICES = [
        (OWNER, '사장님'),
        (CUSTOMER, '고객님'),
    ]
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    
    
    def profile_image_path(instance, filename):
        return f'profile/{instance.username}/{filename}'
    
    
    image = ProcessedImageField(upload_to=profile_image_path, blank=True, null=True)
    region = models.CharField(max_length=10, choices=REGION_CHOICES, default='서울')
    is_owner = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='고객님')
    address = models.CharField(max_length=200)


    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
        super(User, self).delete(*args, **kargs)


    def save(self, *args, **kwargs):
        if self.id:
            old_user = User.objects.get(id=self.id)
            if self.image != old_user.image:
                if old_user.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_user.image.path))
        super(User, self).save(*args, **kwargs)    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from imagekit.forms import ProcessedImageField
from imagekit.processors import ResizeToFill
from django import forms
from django.forms.widgets import ClearableFileInput


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'last_name', 'email', 'image', 'is_owner', 'region',)
    
    REGION_CHOICES = [
        ('서울', '서울'), ('인천', '인천'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('광주', '광주'), ('대전', '대전'), ('세종특별자치시', '세종특별자치시'), ('제주특별자치도', '제주특별자치도'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'),
    ]
    
    USER_TYPE_CHOICES = [
        ('사장님', '사장님'), ('고객님', '고객님'),
    ]
    username = forms.CharField(label=False, label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-box','placeholder' : '아이디','style' : 'width:400px;'}))
    password1 = forms.CharField(label=False, label_suffix='', widget=forms.PasswordInput(
        attrs={'class': 'form-box','placeholder' : '비밀번호','style' : 'width:400px;'}))
    password2 = forms.CharField(label=False, label_suffix='', widget=forms.PasswordInput(
        attrs={'class': 'form-box','placeholder' : '비밀번호 확인','style' : 'width:400px;'}))
    last_name = forms.CharField(label=False, label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-box','placeholder' : '이름','style' : 'width:400px;'}))
    email = forms.EmailField(label=False, label_suffix='', widget=forms.EmailInput(
        attrs={'class': 'form-box','placeholder' : '이메일','style' : 'width:400px;'}))
    region = forms.ChoiceField(label='선호지역', label_suffix='', choices=REGION_CHOICES, widget=forms.Select(
        attrs={'class': 'select--box','style' : 'width:195px;'}))
    image = ProcessedImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-box','style' : 'width:400px;'}),
        label='프로필 이미지',
        label_suffix='',
        spec_id='image_size',
    )
    is_owner = forms.ChoiceField(label='유저 타입', label_suffix='', choices=USER_TYPE_CHOICES, widget=forms.Select(
        attrs={'class': 'select--box','style' : 'width:195px;'}))


class CustomClearableFileInput(ClearableFileInput):
    template_name = 'posts/custom_clearable_file_input.html'


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('last_name', 'image', 'email', 'is_owner', 'region',)
    last_name = forms.CharField(label=False, label_suffix='', widget=forms.TextInput(
        attrs={'class': 'form-box','placeholder' : '이름','style' : 'width:400px;'}))
    
    REGION_CHOICES = [
        ('서울', '서울'), ('인천', '인천'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('광주', '광주'), ('대전', '대전'), ('세종특별자치시', '세종특별자치시'), ('제주특별자치도', '제주특별자치도'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'),
    ]
    
    USER_TYPE_CHOICES = [
        ('사장님', '사장님'), ('고객님', '고객님'),
    ]
    
    email = forms.EmailField(label='이메일', label_suffix='', widget=forms.EmailInput(
        attrs={'class': 'form-box','placeholder' : '이메일','style' : 'width:400px;'}))
    region = forms.ChoiceField(label='선호지역', label_suffix='', choices=REGION_CHOICES, widget=forms.Select(
        attrs={'class': 'select--box','style' : 'width:195px;'}))
    image = ProcessedImageField(
        required=False,
        widget=CustomClearableFileInput(attrs={'class': 'form-box','style' : 'width:400px;'}),
        label='프로필 이미지',
        label_suffix='',
        spec_id='image_size',
    )

    is_owner = forms.ChoiceField(label='유저 타입', label_suffix='', choices=USER_TYPE_CHOICES, widget=forms.Select(
        attrs={'class': 'select--box','style' : 'width:195px;'}))
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password')
 

class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('old_password', 'new_password1', 'new_password2',)
    old_password = forms.CharField(label=False, label_suffix='', widget=forms.PasswordInput(
        attrs={'class': 'form-box','placeholder' : '기존 비밀번호','style' : 'width:400px;'}))
    new_password1 = forms.CharField(label=False, label_suffix='', widget=forms.PasswordInput(
        attrs={'class': 'form-box','placeholder' : '새 비밀번호','style' : 'width:400px;'}))
    new_password2 = forms.CharField(label=False, label_suffix='', widget=forms.PasswordInput(
        attrs={'class': 'form-box','placeholder' : '새 비밀번호 확인','style' : 'width:400px;'}))
    
    
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label=False,
        widget=forms.TextInput(
            attrs = {
                'class': 'form-box',
                'placeholder' : '아이디',
                'style' : 'width:400px; cursor: text;'
            }
        )
    )
    password = forms.CharField(
        label=False,
        widget=forms.PasswordInput(
            attrs = {
                'class': 'form-box',
                'placeholder' : '비밀번호',
                'style' : 'width:400px; cursor: text;'
            }
        )
    )
    

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm, CustomAuthenticationForm
from posts.models import Post
from django.http import JsonResponse
from schedules.models import Schedule
import os
from django.urls import reverse_lazy
from posts.models import Priority
from django.db.models.functions import TruncMonth
from django.db.models import Count
from django.utils import timezone
from django.core import serializers
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from my_messages.models import Message


# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.address = request.POST.get('address')
            user.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            prev_url = request.session.get('prev_url')
            if prev_url:          
                del request.session['prev_url']
                return redirect(prev_url)
            return redirect('main')
        return redirect('accounts:login')
    else:
        form = CustomAuthenticationForm()
        request.session['prev_url'] = request.META.get('HTTP_REFERER')
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('main')
    

@login_required
def delete(request):
    request.user.delete()
    return redirect('main')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.address = request.POST.get('address')
            user.save()
            return redirect('accounts:profile', request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('main')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

    
@login_required
def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    user_id = request.user.id
    like_post = person.like_posts.all()
    liked_posts = like_post.exclude(priority__user=request.user)
    # priority_range = range(1, 11)
    # priority_range2 = range(6, 11)
    priorities = Priority.objects.filter(user=request.user).order_by('priority')
    schedules = Schedule.objects.filter(user_id=user_id, start__gte=timezone.now()).order_by('start__date', 'end__date')
    messages = Message.objects.filter(receiver=request.user)
    sentmessages = Message.objects.filter(sender=request.user)

    context = {
        'person': person,
        'followings': person.followings.all(),
        'followers': person.followers.all(),
        'priorities': priorities,
        'schedules': schedules,
        'liked_posts': liked_posts,
        'messages': messages,
        'sentmessages': sentmessages,
    }

    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)


@login_required
def following_list(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    followings = person.followings.all()
    context = {
        'followings': followings,
        }
    return render(request, 'accounts/following_list.html', context)


@login_required
def followers_list(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    followers = person.followers.all()
    context = {
        'followers': followers,
        }
    return render(request, 'accounts/followers_list.html', context)

def priority_list(request, username):
    user_id = request.user.id
    User = get_user_model()
    person = User.objects.get(username=username)
    priorities = Priority.objects.filter(user=person).order_by('priority')
    data = []
    for priority in priorities:
        post_data = serializers.serialize('python', [priority.post])[0]
        post = post_data['fields']
        post['pk'] = post_data['pk']
        data.append({'post': post})
    return JsonResponse(data, safe=False)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %} 
{% block title %}Password{% endblock title %} 
{% load static %}
{% block head %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">  
{% endblock head %}
{% block content %}
<div class="accounts--box">
  <p class="accounts--title">비밀번호 변경</p>
  <form action="{% url 'accounts:change_password' %}" method="POST" enctype="multipart/form-data" onsubmit="finish(event)">
    {% csrf_token %}
    <p>{{ form.old_password }}</p>
    <p>{{ form.new_password1 }}</p>
    <p>{{ form.new_password2 }}</p>
    <div class="btn--box">
      <input type="submit" value="저장" class="accounts--btn">
      <input type="button" value="뒤로가기"  class="accounts--btn" onclick="window.history.back()">
    </div>
  </form>
</div>
{% endblock content %}
{% block script %}
<script>
  function finish(event) {
    event.preventDefault(); 
    alert("비밀번호가 성공적으로 변경되었습니다.");
    
    var form = event.target;
    form.submit();
  }
</script>
{% endblock script %}

accounts/templates/accounts/followers_list.html
{% extends 'empty.html' %}
{% load static %}
{% block content %}
<ul id="follower-ul">
  {% for follower in followers %}
  <li class="follow--modal">
    <a href="{% url 'accounts:profile' follower.username %}">
      {% if follower.image %}
        <div class="profile--image rounded-circle">
          <img src="{{ follower.image.url }}" alt="follower image" class="object-fit-fill profile">
        </div>
      {% else %}
        <div class="profile--image rounded-circle">
          <img src="{% static 'image/profile-none.png' %}" alt="follower image" class="object-fit-fill profile">
        </div>
      {% endif %}
      {{ follower.username }}
    </a>
  </li>
  {% empty %}
  <p class="ms-2">팔로워가 없습니다.</p>
  {% endfor %}
</ul>
{% endblock content %}

accounts/templates/accounts/following_list.html
{% extends 'empty.html' %}
{% load static %}
{% block content %}
<ul id="following-ul">
  {% for following in followings %}
  <li class="follow--modal">
    <a href="{% url 'accounts:profile' following.username %}">
      {% if following.image %}
        <div class="profile--image rounded-circle">
          <img src="{{ following.image.url }}" alt="following image" class="object-fit-fill profile">
        </div>
      {% else %}
        <div class="profile--image rounded-circle">
          <img src="{% static 'image/profile-none.png' %}" alt="following image" class="object-fit-fill profile">
        </div>
      {% endif %}
      {{ following.username }}
    </a>
  </li>
  {% empty %}
  <p class="ms-2">팔로잉이 없습니다.</p>
  {% endfor %}
</ul>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %} 
{% block title %}Login{% endblock title %} 
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">  
{% endblock head %}
{% block content %}
<div class="accounts--box">
  <p class="accounts--title">
    {% load socialaccount %}
    <a href="{% provider_login_url 'kakao' method='oauth2' %}" class="social--login">
      <img src="{% static 'image/Kakao.png' %}" alt="" class="social--logo">
    </a>
    로그인
    <a href="{% provider_login_url 'google' method='oauth2' %}" class="social--login">
      <img src="{% static 'image/google.png' %}" alt="" class="social--logo">
    </a>
  </p>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <div class="btn--box">
      <input type="submit" value="로그인" class="accounts--btn">
      <a type="button" href="{% url 'accounts:signup' %}" class="accounts--btn">회원가입</a>
      <input type="submit" value="뒤로가기"  class="accounts--btn" onclick=window.history.back()>
    </div>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} 
{% block title %}SignUP{% endblock title %} 
{% load static %}
{% block head %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">  
{% endblock head %}
{% block content %}
<div class="accounts--box">
  <p class="accounts--title">회원가입</p>
  <form action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.username }}</p>
    <p>{{ form.password1 }}</p>
    <p>{{ form.password2}}</p>
    <p>{{ form.last_name }}</p>
    <p>{{ form.email }}</p>
    <p class="label--box">{{ form.region.label}}</p><p class="label--box">{{ form.is_owner.label}}</p>
    <div class="d-flex gap-1">{{ form.region }}{{ form.is_owner }}</div>
    <div class="mt-2">{{ form.image.label}}{{ form.image }}</div>
    <div class="address--box">
      <input type="text" id="s_address" placeholder="주소" name="address" class="form-address">
      <input type="button" onclick="search_address()" value="주소 검색" class="address--btn">
    </div>
    <div class="btn--box">
      <input type="submit" value="회원가입" class="accounts--btn">
      <a type="button" href="{% url 'accounts:login' %}" class="accounts--btn">로그인</a>
      <input type="submit" value="뒤로가기"  class="accounts--btn" onclick=window.history.back()>
    </div>
  </form>
</div>
{% endblock content %}
{% block script %}
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script src="{% static '/js/accounts_signup.js' %}" type="text/javascript"></script>
{% endblock script %}

accounts/templates/accounts/update.html
{% extends 'base.html' %} 
{% block title %}Update{% endblock title %} 

{% load static %}

{% block head %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">  
{% endblock head %}
{% block content %}
<div class="accounts--box">
  <p class="accounts--title">회원정보 수정</p>
  <form action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data"  onsubmit="finish(event)">
    {% csrf_token %}
    <p>{{ form.last_name }}</p>
    <p>{{ form.email }}</p>
    <p class="label--box">{{ form.region.label}}</p><p class="label--box">{{ form.is_owner.label}}</p>
    <div class="d-flex gap-1">{{ form.region }}{{ form.is_owner }}</div>
    <div class="mt-2">{{ form.image.label}}{{ form.image }}</div>
    <div class="address--box">
      <input type="text" id="s_address" placeholder="주소" name="address" value="{{ user.address }}" class="form-address">
      <input type="button" onclick="search_address()" value="주소 검색" class="address--btn">
    </div>
    <div class="btn--box">
      <input type="submit" value="저장" class="accounts--btn">
      <a type="button" href="{% url 'accounts:change_password' %}" class="accounts--btn">비밀번호 변경</a>
      <input type="submit" value="뒤로가기"  class="accounts--btn" onclick=window.history.back()>
    </div>
  </form>
</div>
{% endblock content %}
{% block script %}
<script>
  function finish(event) {
    event.preventDefault(); 
    alert("성공적으로 변경되었습니다.");
    
    var form = event.target;
    form.submit();
  }
</script>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script src="{% static '/js/accounts_update.js' %}" type="text/javascript"></script>
{% endblock script %}