camping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from .views import main, get_weather


urlpatterns = [
    path('', views.main, name='main'),
    path('get-weather/', get_weather, name='get-weather'),
    path('sales/', views.sales, name='sales'),
    path('get_posts_by_sido/', views.get_posts_by_sido, name='get_posts_by_sido'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('reviews/', include('reviews.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
    path('schedules/', include('schedules.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.urls import path
from .views import MessageCreateView, MessageListView, SentMessagesView, ReplyMessageView
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('send/', MessageCreateView.as_view(), name='send_message'),
    path('inbox/', MessageListView.as_view(), name='inbox_messages'),
    path('sent/', SentMessagesView.as_view(), name='sent_messages'),
    path('reply/<int:sender_id>/', ReplyMessageView.as_view(), name='reply'),
    path('<int:message_pk>/delete/', views.delete, name='delete'),
    path('send/<int:message_pk>/', views.send_detail, name='send_detail'),
    path('receive/<int:message_pk>/', views.receive_detail, name='receive_detail'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:category>', views.category, name='category'),
    path('city/', views.city, name='city'),
    path('theme/', views.theme, name='theme'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/visits/', views.visits, name='visits'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
    path('update_priority_lists/', views.update_priority_lists, name='update_priority_lists'),
]

my_messages/models.py
from django.db import models
from django.conf import settings


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} -> {self.receiver}: {self.content}"

my_messages/forms.py
from django import forms
from .models import Message
from django.contrib.auth import get_user_model


class MessageForm(forms.ModelForm):
    receiver = forms.ModelChoiceField(queryset=get_user_model().objects.all(), empty_label=None)

    class Meta:
        model = Message
        fields = ['receiver', 'content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5}),
        }


class ReplyMessageForm(forms.ModelForm):
    receiver = forms.ModelChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.Select(attrs={'readonly': True, 'id':'reply'})
    )
    class Meta:
        model = Message
        fields = ['receiver', 'content']

my_messages/views.py
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Message
from .forms import ReplyMessageForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ['receiver', 'content']

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        message_pk = self.object.pk
        return reverse('my_messages:send_detail', kwargs={'message_pk': message_pk})


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'accounts/profile.html'
    context_object_name = 'messages'

    def get_queryset(self):
        return Message.objects.filter(receiver=self.request.user)


class SentMessagesView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'my_messages/sent_messages.html'
    context_object_name = 'messages'

    def get_queryset(self):
        return Message.objects.filter(sender=self.request.user)


class ReplyMessageView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = ReplyMessageForm
    
    def get_initial(self):
        initial = super().get_initial()
        User = get_user_model()
        sender = get_object_or_404(User, id=self.kwargs['sender_id'])
        initial['receiver'] = sender.id
        return initial

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.receiver = get_object_or_404(get_user_model(), id=self.kwargs['sender_id'])
        return super().form_valid(form)
    
    def get_success_url(self):
        message_pk = self.object.pk
        return reverse('my_messages:send_detail', kwargs={'message_pk': message_pk})
    
    
def delete(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    message.delete()
    return redirect('accounts:profile', request.user)


def send_detail(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    context = {
        'message': message,
    }
    return render(request, 'my_messages/send_detail.html', context)


def receive_detail(request, message_pk):
    message = Message.objects.get(pk=message_pk)
    context = {
        'message': message,
    }
    return render(request, 'my_messages/receive_detail.html', context)

my_messages/templates/my_messages/message_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
  <link rel="stylesheet" href="/src/plugins/select2-4.0.13/dist/css/select2.min.css">
  <script type="text/javascript" src="/src/plugins/select2-4.0.13/dist/js/select2.min.js"></script>
{% endblock head %}
{% block content %}
<div class="message">
  <h2><input type="submit" value="<"  class="back" onclick=window.history.back()>쪽지보내기</h2>
  <div class="d-flex flex-column justify-content-center align-items-center">
    <form method="POST">
      {% csrf_token %}
      <div class="message--title" style="text-align:start; margin-left:0;">받는이 : {{ form.receiver }}</div>
      {{ form.content }}
      <button type="submit" class="message--btn--submit">Send</button>
    </form>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('#id_receiver').select2(); 
});
</script>
{% endblock %}

my_messages/templates/my_messages/message_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}
{% block content %}
  <div class="message">
      <h2>받은 쪽지함<i class="bi bi-envelope-heart ms-2"></i></h2>
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li>
            <div class="message--box">
              <div class="message--sender">보낸이 :<span class="message--sender" style="margin-left:5px;">{{ message.sender }} <a href="{% url 'my_messages:reply' message.sender.id %}">
                <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
                <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')">삭제</a>
              </div>
              <div class="message--title">받은시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
              <div class="message--txt">{{ message.content }}</div>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>받은 쪽지가 없습니다.</p>
    {% endif %}
  </div>
{% endblock %}

my_messages/templates/my_messages/receive_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}
{% block content %}
  <div class="message--detail">
    <input type="submit" value="<"  class="back2" onclick=window.history.back()>
    <div class="message--sender">보낸이 :<span class="message--sender" style="margin-left:5px;">{{ message.sender.username }} 
      <a href="{% url 'my_messages:reply' message.sender.id %}">
      <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
      <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')"><i class="bi bi-trash3"></i></a>
    </div>
    <div class="message--title">보낸시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
    <div class="message--txt">{{ message.content }}</div>
  </div>
{% endblock %}

my_messages/templates/my_messages/send_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}
{% block content %}
  <div class="message--detail">
    <input type="submit" value="<"  class="back2" onclick=window.history.back()>
    <div class="message--sender">받는이 :<span class="message--sender" style="margin-left:5px;">{{ message.receiver.username }} 
      <a href="{% url 'my_messages:reply' message.receiver.id %}">
      <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
      <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')"><i class="bi bi-trash3"></i></a>
    </div>
    <div class="message--title">보낸시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
    <div class="message--txt">{{ message.content }}</div>
  </div>
{% endblock %}

my_messages/templates/my_messages/sent_messages.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}">
{% endblock head %}
{% block content %}
  <div class="message">
    <h2>보낸 쪽지함<i class="bi bi-envelope-open-heart  ms-2"></i></h2>
    {% if messages %}
      <ul>
      {% for message in messages %}
        <li>
          <div class="message--box">
            <div class="message--sender">받는이 :<span class="message--sender" style="margin-left:5px;">{{ message.receiver.username }} 
              <a href="{% url 'my_messages:reply' message.receiver.id %}">
              <i class="bi bi-envelope-paper-heart chat--btn--txt"></i></a></span>
              <a href="{% url 'my_messages:delete' message.pk %}" onclick="return confirm('삭제하시겠습니까?')">삭제</a>
            </div>
            <div class="message--title">보낸시간 :<span class="message--title" style="margin-left:5px; font-family: 'LeeSeoyun';">{{ message.timestamp }}</span></div>
            <div class="message--txt">{{ message.content }}</div>
          </div>
        </li>
      {% endfor %}
      </ul>
    {% else %}
      <p>보낸 쪽지가 없습니다.</p>
    {% endif %}
  </div>
{% endblock %}