accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<str:username>/following-list/', views.following_list, name='following_list'),
    path('profile/<str:username>/followers-list/', views.followers_list, name='followers_list'),
    path('priority_list/<str:username>/', views.priority_list, name='priority_list'),
]

camping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from .views import main, get_weather


urlpatterns = [
    path('', views.main, name='main'),
    path('get-weather/', get_weather, name='get-weather'),
    path('sales/', views.sales, name='sales'),
    path('get_posts_by_sido/', views.get_posts_by_sido, name='get_posts_by_sido'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('reviews/', include('reviews.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'^upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path(r'^browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),
    path('schedules/', include('schedules.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:category>', views.category, name='category'),
    path('city/', views.city, name='city'),
    path('theme/', views.theme, name='theme'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/visits/', views.visits, name='visits'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('search/', views.search, name='search'),
    path('tags/<int:tag_pk>/', views.tagged_posts, name='tagged_posts'),
    path('update_priority_lists/', views.update_priority_lists, name='update_priority_lists'),
]

schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'
urlpatterns = [
    path('calendar/', views.calendar, name='calendar'),
    path('create/', views.create_schedule, name='create'),
    path('detail/<int:schedule_id>/', views.detail_schedule, name='detail'),
    path('update/<int:schedule_id>/', views.update_schedule, name='update'),
    path('delete/<int:schedule_id>/', views.delete_schedule, name='delete'),
    path('get_schedule_data/', views.get_schedule_data, name='get_schedule_data'),
]

schedules/models.py
from django.db import models
from django.urls import reverse
from posts.models import Post
from django.conf import settings


class Schedule(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='schedules')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    start = models.DateTimeField()
    end = models.DateTimeField()
    description = models.TextField()
    address = models.CharField(max_length=200)
    extra_address = models.CharField(max_length=200)
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='participating', blank=True)
    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'post_pk': str(self.post.pk)})

    def __str__(self):
        return self.title, self.address, self.extra_address

schedules/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from .models import Schedule, Post
from django.urls import reverse
from utils.map import get_latlng_from_address
import os
from django.contrib import messages
from django.contrib.auth import get_user_model
import math
from datetime import datetime, date


@login_required
def calendar(request):
    posts = Post.objects.all()
    users = get_user_model().objects.exclude(id=request.user.id)
    posts = Post.objects.all()
    kakao_script_key = os.getenv('kakao_script_key')
    user_id = request.user.id
    schedules = Schedule.objects.filter(user_id=user_id)
    latitude_list = []
    longitude_list = []
    
    for schedule in schedules:
        address = schedule.post.address
        latitude, longitude = get_latlng_from_address(address)
        latitude_list.append(latitude)
        longitude_list.append(longitude)
    
    context = {
        'posts': posts,
        'schedules': schedules,
        'kakao_script_key': kakao_script_key,
        'latitude_list': latitude_list,
        'longitude_list': longitude_list,
        'users': users,
    }
    return render(request, 'schedules/calendar.html', context)


@login_required
def create_schedule(request):
    users = get_user_model().objects.exclude(id=request.user.id)
    posts = Post.objects.all()
    if request.method == 'POST':
        post_id = request.POST['post_id']
        start = request.POST['start']
        end = request.POST['end']
        description = request.POST['description']
        participants = request.POST.getlist('participants')
        
        post = get_object_or_404(Post, id=post_id)
        
        schedule = Schedule(
            post=post,
            user=request.user,
            title=post.title,
            start=start,
            end=end,
            description=description,
            address=post.address,
            extra_address=post.extra_address
        )
        schedule.save()

        schedule.participants.set(participants)
        
        return redirect(reverse('schedules:calendar'))

    context = {
        'posts': posts,
        'users': users,
    }
    return render(request, 'schedules/calendar.html', context)


@login_required
def get_schedule_data(request):
    schedules = Schedule.objects.filter(user=request.user)
    data = []
    for schedule in schedules:
        url = reverse('schedules:update', kwargs={'schedule_id': schedule.id}) 
        event_data = {
            'title': schedule.title,
            'start': schedule.start.isoformat(),
            'end': schedule.end.isoformat(),
            'url': url
        }
        data.append(event_data)
    return JsonResponse(data, safe=False)


def update_schedule(request, schedule_id):
    schedule = get_object_or_404(Schedule, id=schedule_id)
    users = get_user_model().objects.exclude(id=request.user.id)
    participants = schedule.participants.all()

    if request.method == 'POST':
        schedule.post_id = request.POST['post_id']
        schedule.title = schedule.post.title
        schedule.start = request.POST['start']
        schedule.end = request.POST['end']
        schedule.description = request.POST['description']

        selected_participants = request.POST.getlist('participants')
        schedule.participants.set(selected_participants)

        schedule.save()
        return redirect('schedules:calendar')

    context = {
        'schedule': schedule,
        'schedule_id': schedule_id,
        'participants': participants,
        'users': users,
    }

    return render(request, 'schedules/calendar.html', context)


def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371 
    lat1, lon1, lat2, lon2 = float(lat1), float(lon1), float(lat2), float(lon2)
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat/2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon/2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    distance = R * c

    return round(distance)


@login_required
def detail_schedule(request, schedule_id):
    kakao_script_key = os.getenv('kakao_script_key')
    kakao_key = os.getenv('kakao_key')
    schedule = get_object_or_404(Schedule, id=schedule_id)
    address = schedule.address
    latitude, longitude = get_latlng_from_address(address)
    participants = schedule.participants.all()
    u_address = request.user.address
    u_latitude, u_longitude = get_latlng_from_address(u_address)
    distance = calculate_distance(latitude, longitude, u_latitude, u_longitude)
    start_date = schedule.start.date()
    current_date = date.today()
    d_day = (start_date - current_date).days
    title = schedule.post.title
    
    context = {
        'schedule': schedule,
        'kakao_script_key': kakao_script_key,
        'kakao_key': kakao_key,
        'latitude': latitude,
        'longitude': longitude,
        'participants': participants,
        'u_latitude': u_latitude,
        'u_longitude': u_longitude,
        'distance': distance,
        'd_day': d_day,
        'title': title,
    }
    
    return render(request, 'schedules/detail.html', context)


@login_required
def delete_schedule(request, schedule_id):
    schedule = Schedule.objects.get(id=schedule_id)
    if request.user == schedule.user:
        schedule.delete()
        messages.success(request, '일정이 삭제되었습니다.')
    else:
        messages.error(request, '일정을 삭제할 권한이 없습니다.')
    return redirect('schedules:calendar')

schedules/templates/schedules/calendar.html
{% extends 'base.html' %} 
{% block title %}일정{% endblock title %} 
{% load static %}
{% block head %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="/src/plugins/select2-4.0.13/dist/css/select2.min.css">
<script type="text/javascript" src="/src/plugins/select2-4.0.13/dist/js/select2.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}"> 
{% endblock head %}
{% block content %}
<div class="wid">

  <!-- 진짜 달력 본체 -->
  <div id='calendar'></div>

  <hr>
  <div class="plan">
    <p class="schedule--plus">일정 추가 </p>
    <form method="POST" action="{% url 'schedules:create' %}" class="plan--form">
      {% csrf_token %}
      <div class="add_plan">
        <div class="plan-item">
          <label for="post">캠핑 장소:</label>
          <select name="post_id" id="post">
            {% for post in posts %}
            <option value="{{ post.id }}">{{ post.title }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="plan-item">
          <label for="participants">동행자:</label>
          <button type="button" data-bs-toggle="modal" data-bs-target="#participantModal" class="par-btn">검색 <i class="bi bi-search"></i></button>
    
          <div class="modal fade" id="participantModal" tabindex="-1" role="dialog" aria-labelledby="participantModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="participantModalLabel">동행자 선택</h5>
                </div>
                <div class="modal-body">
                  <div class="participant-list">
                    {% for user in users %}
                      <div class="d-flex align-self-center">
                        <input type="checkbox" id="participant_{{ user.id }}" name="participants" value="{{ user.id }}" style="margin-right: 0.5rem;">
                        <label for="participant_{{ user.id }}">{{ user.username }}</label>
                      </div>
                    {% endfor %}
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="save-btn" data-bs-dismiss="modal">저장</button>
                  <button type="button" data-bs-dismiss="modal" class="par-btn">닫기</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="plan-item">
          <label for="start">시작일:</label>
          <input type="datetime-local" name="start" id="start">
        </div>
        <div class="plan-item">
          <label for="end">종료일:</label>
          <input type="datetime-local" name="end" id="end">
        </div>
        <div class="plan-item">
          <label for="description">메모:</label>
          <input type="textarea" name="description" id="description">
        </div>
      </div>
      <input type="submit" value="일정 생성" class="plan--save">
    </form>
    <a href="{% url 'accounts:profile' request.user %}" class="calendar--profile">프로필보기</a>
  </div>
  <hr>

  <ul style="list-style-type: none; padding: 0; margin: 0;">
    {% for schedule in schedules %}
    <li class="schedule--list">
      <div class="schedule--li">
        <p>{{ forloop.counter }}.</p>
        <p>장소 : </p>
        <p><a href="{% url 'posts:detail' post_pk=schedule.post.pk %}" id="schedule--title">{{ schedule.title }}</a></p>
        <p>날짜 : {{ schedule.start|date:"m월 d일" }}부터</p>
        <p>{{ schedule.end|date:"m월 d일" }}까지</p>
        <!-- 모달 트리거 버튼 -->
        <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{ schedule.id }}" class="calendar--btn">일정 변경</button>
        <a href="{% url 'schedules:delete' schedule.id %}" onclick="return confirm('일정을 삭제하시겠습니까?')" class="calendar--btn">삭제</a>
      </div>
    
      <!-- 일정 변경 모달 -->
      <div class="modal fade mt-5" id="exampleModal{{ schedule.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">일정 변경</h1>
            </div>
            <div class="modal-body">
              <form method="POST" action="{% url 'schedules:update' schedule_id=schedule.id %}">
                {% csrf_token %}
                <p>
                  <label for="post">캠핑 장소:</label>
                  <select name="post_id" id="post_id">
                    {% for post in posts %}
                    <option value="{{ post.id }}" {% if post.id == schedule.post.id %}selected{% endif %}>{{ post.title }}</option>
                    {% endfor %}
                  </select>
                </p>
                <p>
                  <label for="participants">동행자:</label>
                  <ul style="list-style: none;">
                    {% for user in users %}
                      <li>
                        <input type="checkbox" name="participants" value="{{ user.id }}"
                          {% if user in schedule.participants.all %}checked{% endif %}>
                        {{ user.username }}
                      </li>
                    {% endfor %}
                  </ul>
                </p>          
                <p>
                  <label for="start">시작일:</label>
                  <input type="datetime-local" name="start" id="start" value="{{ schedule.start|date:'Y-m-d\TH:i' }}"> 
                </p>
                <p>
                  <label for="end">종료일:</label>
                  <input type="datetime-local" name="end" id="end" value="{{ schedule.end|date:'Y-m-d\TH:i' }}">
                </p>
                <p>
                  <label for="description">메모:</label>
                  <input type="textarea" name="description" id="description" value="{{ schedule.description }}">
                </p>
                <div class="modal-footer">
                  <input type="submit" class="save-btn" value="일정 변경">
                  <button type="button" class="par-btn" data-bs-dismiss="modal">닫기</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </li>  
    {% endfor %}
  </ul>

</div>
{% endblock content %}
{% block script %}
<script src='{% static "js/index.global.js" %}'></script>
<script src='{% static "js/calendar.js" %}'></script>
{% comment %} <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={{ kakao_script_key }}&libraries=services"></script> {% endcomment %}
{% comment %} <script src="{% static '/js/posts_detail_map.js' %}" type="text/javascript"></script> {% endcomment %}
<script>
    $(document).ready(function() {
      $('#post').select2(); 
  });
</script>
<script>
  $(document).ready(function() {
    $('#participantModal').modal();
  });
</script>
{% endblock script %}

schedules/templates/schedules/detail.html
{% extends 'base.html' %}
{% block title %}일정 - {{ schedule.title }}{% endblock title %} 
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'js/posts_detail_map.js' %}" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/schedule_detail.css' %}"> 
{% endblock head %}
{% block content %}
<div class="detail--header">
  <div class="detail--title">
    <h2>내 일정 (D-DAY {{ d_day }})</h2>
    <div class="detail--title__align">
      <div class="detail--title__location m">
        캠핑 장소: <a href="{% url 'posts:detail' post_pk=schedule.post.pk %}">{{ schedule.title }}</a>
      </div>
      <div class="detail--rating">
        <i class="bi bi-star-fill"></i> 
        {{ schedule.post.rating }}
      </div>
    </div>
  </div>
  {% if participants %}
    <div class="detail--participants">
      <div class="participant--title">
        동행자
      </div>
      <div class="detail__participants">
        {% for participant in participants %}
          <a href="{% url 'accounts:profile' participant.username %}">{{participant}}</a>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <div class="btn--box">
    <a href="" onclick="copy_trackback(this.href); return false;" class="icon-btn"><i class="bi bi-link-45deg"></i></a>
    <a href="" onclick="printThis(); return false;" class="icon-btn"><i class="bi bi-printer"></i></a>
    <button class="icon-btn map-btn" id="map-btn" style="border:none;"><i class="bi bi-arrow-90deg-right"></i></button>
  </div>
</div>

<div class="detail--info">
  <div class="map" id="map" data-longitude="{{ longitude }}" data-latitude="{{ latitude }}">
    <p class="detail--address">
      {{ schedule.post.address }}<br>
      {{ schedule.post.extra_address }}
    </p>
  </div>
  <div class="info--box">
    <p><span class="info--title">일정</span>{{ schedule.start }} ~ {{ schedule.end }}</p><hr>
    <p><span class="info--title">주소</span>{{ schedule.post.address }} {{ post.extra_address }} ({{ distance }} km)</p><hr>
    <p><span class="info--title">문의처</span>{{ schedule.post.phone }}</p><hr>
    <p><span class="info--title">입실시간</span>{{ schedule.post.open_hour }}</p><hr>
    <p><span class="info--title">퇴실시간</span>{{ schedule.post.close_hour }}</p><hr>
    <p><span class="info--title">캠핑장 유형</span>{{ schedule.post.category }}</p><hr>
    <p><span class="info--title">캠핑장 환경</span>{{ schedule.post.nature}}</p>
  </div>
</div>

<div class="camp--title">메모</div>
<div class="content--box">
  <div class="content--info">
    {{ schedule.description }}
  </div>
</div>

{% endblock content %}
{% block script %}
<script src='{% static "js/index.global.js" %}'></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={{ kakao_script_key }}&libraries=services"></script>
<script>
  function copy_trackback(url) {
    var tempInput = document.createElement('input');
    tempInput.value = url;
    document.body.appendChild(tempInput);
    tempInput.select();
    document.execCommand('copy');
    document.body.removeChild(tempInput);
    alert('URL이 복사되었습니다.');
  }
  
  function printThis() {
    window.print();
  }
</script>
<script>
  window.addEventListener('DOMContentLoaded', function() {
      const longitude = document.getElementById('map').getAttribute('data-longitude');
      const latitude = document.getElementById('map').getAttribute('data-latitude');
      const container = document.getElementById('map');
      const options = {
          center: new kakao.maps.LatLng(latitude, longitude),
          level: 3
      };
      const map = new kakao.maps.Map(container, options);
      const markerPosition = new kakao.maps.LatLng(latitude, longitude);
      const marker = new kakao.maps.Marker({
          position: markerPosition
      });
      marker.setMap(map);
  });
</script>
<script>
  document.getElementById("map-btn").addEventListener("click", function() {
    const apiKey = "{{ kakao_key }}";
    const apiUrl = "https://dapi.kakao.com/v2/local/geo/transcoord.json?x=127.423084&y=37.078956&input_coord=WGS84&output_coord=TM";
  
    fetch(apiUrl, {
      headers: {
        "Authorization": "KakaoAK " + apiKey
      }
    })
    .then(response => response.json())
    .then(data => {
      const latitude = "{{ latitude }}";
      const longitude = "{{ longitude }}";
      const title = "{{ title }}";
  
      const directionsUrl = "https://map.kakao.com/link/to/" + title + "," + latitude + "," + longitude;
    
      window.open(directionsUrl, "_blank");
    })
    .catch(error => {
      console.log(error);
    });
  });
</script>
{% endblock script %}